#!/bin/sh

psql -c "CREATE USER ${CKAN_POSTGRES_USER} \
    WITH PASSWORD '${CKAN_POSTGRES_PWD}' \
    NOSUPERUSER NOCREATEDB NOCREATEROLE;"

createdb -e -O ${CKAN_POSTGRES_USER} ${CKAN_POSTGRES_DB} -E utf-8

if [ "${CKAN_DATASTORE_POSTGRES_DB}" ]; then
    psql -c "CREATE USER ${CKAN_DATASTORE_POSTGRES_READ_USER} \
        WITH PASSWORD '${CKAN_DATASTORE_POSTGRES_READ_PWD}' \
        NOSUPERUSER NOCREATEDB NOCREATEROLE;"

    if [ "${CKAN_DATASTORE_POSTGRES_WRITE_USER}" ] && [ "${CKAN_DATASTORE_POSTGRES_WRITE_PWD}"  ]; then
        psql -c "CREATE USER ${CKAN_DATASTORE_POSTGRES_WRITE_USER} \
            WITH PASSWORD '${CKAN_DATASTORE_POSTGRES_WRITE_PWD}' \
            NOSUPERUSER NOCREATEDB NOCREATEROLE;"
    fi

    createdb -e -O ${CKAN_DATASTORE_POSTGRES_WRITE_USER} ${CKAN_DATASTORE_POSTGRES_DB} -E utf-8
fi
